port : "8080"

db:
  username: "postgres"
  host : "localhost"
  port : "5432"
  dbname : "postgres"
  sslmode : "disable"
  password : "postgres"

tg:
  bot-token : "5427941656:AAHCBMvIo5iu6Sgtxm0hnXwAE3E9gKsK9fI"